# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-26 13:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Artwork',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=200)),
                ('created_on', models.DateField(blank=True, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='artwork/')),
            ],
        ),
        migrations.CreateModel(
            name='ArtworkContext',
            fields=[
                ('created_for', models.SlugField(primary_key=True, serialize=False, unique=True)),
                ('description', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='artwork',
            name='created_for',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='artwork.ArtworkContext'),
        ),
    ]
