# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 17:05
from __future__ import unicode_literals

from django.db import migrations
import sorl.thumbnail.fields


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='artwork',
            name='image',
            field=sorl.thumbnail.fields.ImageField(blank=True, null=True, upload_to='artwork/'),
        ),
    ]
