# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-30 20:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('artwork', '0002_auto_20160328_1305'),
    ]

    operations = [
        migrations.AddField(
            model_name='artwork',
            name='height',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='medium',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='artwork',
            name='width',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
