# -*- coding: utf-8 -*-
# Generated by Django 1.9.1 on 2016-03-28 15:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('comments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='posted_at',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 3, 28, 15, 20, 47, 389633, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
